server:
  port: 9296

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zaurjabrailov77/cloud-config-server.git
          clone-on-start: true